# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - GridMasterBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Set up Redis password environment variable
        run: echo "CACHE_PASSWORD=${{ secrets.CACHE_PASSWORD }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install

      # SonarCloud Analysis
      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          entryPoint: "/opt/sonar-scanner/bin/sonar-scanner"
          args: >
            -Dsonar.projectKey=jcontreras2693_GridMaster_Backend
            -Dsonar.organization=jcontreras2693
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.java.binaries=target/classes
            -Dsonar.exclusions=**/*.java,**/test/**,**/*Test.java,**/config/**,**/exception/**
            -X

      - name: Upload JaCoCo Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4AD3DE845E9A44D69F349823D2CE7266 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5C051CD04481403D9441D8C73F65F50D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7CB1001F96D4445690581543AA25250C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GridMasterBackend'
          slot-name: 'Production'
          package: '*.jar'
          